### ISSUE TITLE
Support the parsing of CAA records.

### ISSUE THREAD

**Issue by samuelwilliams** [Badcow/DNS-Parser#1]
Parser does not support CAA records.

**Comment by samuelwilliams** [comment]
@skirmis - Did you want to check out the latest DNS-Parser release. You can now add custom rdata handler for CAA. Check out the README.

**Comment by samuelwilliams** [comment]
Check out the latest release of [Badcow DNS](https://github.com/Badcow/DNS). I've merged the parser into the main library and added the CAA parsing fix you've requested here.

**Comment by skirmis** [comment]
Thank you very much, library works as expected! :+1:
